### ISSUE TITLE
Feature Request: Enable support for XCP-NG

### ISSUE THREAD

**Issue by Vrtak-CZ** [sensu/monitoring-plugins#14]
Hi,

can you please enable support for XCP-NG it's based on CentOS 7 so we can use centos build.

I'm just tested it with adding this build definition to asset

```yaml
  - url: https://assets.bonsai.sensu.io/69b7bb9135ace32d37e45bcfc1ea245181f19db9/monitoring-plugins-centos7_2.4.1_linux_amd64.tar.gz
    sha512: bab6cbbca70090f1f51caaa8e419200da8818fc23aa08407b9ef08e8606cf5279118fe567ef7203e4159deafdba59cb627e2a5a6dfc523f3a338f585b2c5ab6f
    filters:
    - entity.system.os == 'linux'
    - entity.system.platform == 'xcp-ng'
    - entity.system.platform_version.split('.')[0] == '8'
    - entity.system.arch == 'amd64'
```

more entity info:

```
OS:                     linux
Platform:               xcp-ng
Platform Family:
Platform Version:       8.1.0
```
